# Generated by Django 4.0.5 on 2022-06-06 15:14

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_avatar_profile_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpost_upvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1653941345/default/pexels-abdul-kayum-10845119_iwtq8i.jpg', max_length=255, null=True, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=cloudinary.models.CloudinaryField(default='v1654350915/default/default_image_nrmi4l.svg', max_length=255, verbose_name='profile_image'),
        ),
    ]
