# Generated by Django 4.0.5 on 2022-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='media/default_post_image.jpg', null=True, upload_to='', verbose_name='post_image'),
        ),
    ]
