# Generated by Django 4.0.5 on 2022-06-07 14:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1653941345/default/pexels-abdul-kayum-10845119_iwtq8i.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1654350915/default/default_image_nrmi4l.svg', max_length=255, verbose_name='image'),
        ),
    ]
