# Generated by Django 4.0.5 on 2022-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_post_image_alter_profile_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(verbose_name='comment body'),
        ),
    ]
